### ISSUE TITLE
Support for null-safety?

### ISSUE THREAD

**Issue by alfredo-handcash** [james-alex/date_time_format#4]
Hi! First of all, thank you for your work and time creating this package, is amazing and help me a lot of times!!

There are any plan to migrate this package to null-safety? I think this is a package that another packages depends on, so there are a roadmap to be migrated?

Thank you!

**Comment by james-alex** [comment]
Hello, a pre-release null-safe version of `date_time_format` has been published to [pub.dev](https://pub.dev/packages/date_time_format/versions/2.0.0-nullsafety).
