### ISSUE TITLE
Abbreviation for 1 month and 1 minute are the same?

### ISSUE THREAD

**Issue by ammarhemani** [james-alex/date_time_format#6]
Hello,
Firstly, thank you for creating an amazing package, this must've taken a lot of your time and effort! 

While using the Relative Formatting functionality, I noticed that the abbreviation for 1 month ago, and 1 minute ago are the same. 

If the DateTime was 1 month ago, and the 'abbr' key is set to true, the String generated would be '1m'.
Similarly, if the DateTime was 1 minute ago, and the 'abbr' key is set to true, the String generated would still be '1m'.

Is there something I'm missing, or is this actually a bug?

Thanks!

**Comment by james-alex** [comment]
Hello, I've been considering this for awhile now and have decided to change the default abbreviation for months to `mo` and add a new parameter, [abbreviations], to allow for custom abbreviations to be provided to the relative formatter.

These changes are now on [pub.dev](https://pub.dev/packages/date_time_format) in v2.0.1.
